// REGISTRATION PAGE START
export const LOAD_REGISTRATION_FORM_DATA = 'LOAD_REGISTRATION_DATA';
export const CLEAR_REGISTRATION_FORM_DATA = 'CLEAR_REGISTRATION_DATA';
// REGISTRATION PAGE END

// COMMUNITY REGISTER PAGE START
export const LOAD_COMMUNITY_FORM_DATA = 'LOAD_COMMUNITY_FORM_DATA';
export const CLEAR_COMMUNITY_FORM_DATA = 'CLEAR_COMMUNITY_FORM_DATA';
// COMMUNITY REGISTER PAGE END

// COMMUNITY INFO DATA START
export const LOAD_COMMUNITY_DATA = 'LOAD_COMMUNITY_DATA';
export const CLEAR_COMMUNITY_DATA = 'CLEAR_COMMUNITY_DATA';
// COMMUNITY INFO DATA END

// LOGIN USER DATA START
export const LOAD_USER_DATA = 'LOAD_LOGIN_DATA';
export const CLEAR_USER_DATA = 'CLEAR_LOGIN_DATA';

export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_CURRENT_COMMUNITY = 'CHANGE_CURRENT_COMMUNITY';

export const LOAD_USER_PERMISSIONS = 'LOAD_USER_PERMISSIONS';
export const CLEAR_USER_PERMISSIONS = 'CLEAR_USER_PERMISSIONS';
// LOGIN USER DATA END

// FILES START
export const LOAD_ALL_FILES = 'LOAD_ALL_FILES';
export const CLEAR_ALL_FILES = 'CLEAR_ALL_FILES';

export const LOAD_SELECTED_IDEA_FILES = 'LOAD_SELECTED_IDEA_FILES';
export const CLEAR_SELECTED_IDEA_FILES = 'CLEAR_SELECTED_IDEA_FILES';

export const LOAD_SELECTED_COMMENT_FILES = 'LOAD_SELECTED_COMMENT_FILES';
export const CLEAR_SELECTED_COMMENT_FILES = 'CLEAR_SELECTED_COMMENT_FILES';

export const LOAD_SELECTED_CHALLENGE_FILES = 'LOAD_SELECTED_CHALLENGE_FILES';
export const LOAD_SELECTED_POST_UPDATE_FILES =
  'LOAD_SELECTED_POST_UPDATE_FILES';
export const CLEAR_SELECTED_CHALLENGE_FILES = 'CLEAR_SELECTED_CHALLENGE_FILES';
export const CLEAR_SELECTED_POST_UPDATE_FILES =
  'CLEAR_SELECTED_POST_UPDATE_FILES';

export const LOAD_SINGLE_FILE = 'LOAD_SINGLE_FILE';
export const CLEAR_SINGLE_FILE = 'CLEAR_SINGLE_FILE';
// FILES END

// PAGE LOADER START
export const SHOW_ACTIVITY_INDICATOR = 'SHOW_ACTIVITY_INDICATOR';
export const HIDE_ACTIVITY_INDICATOR = 'HIDE_ACTIVITY_INDICATOR';
// PAGE LOADER END

// COMMUNITY SETTINGS START
export const LOAD_COMMUNITY_APPEARANCE_SETTINGS =
  'LOAD_COMMUNITY_APPEARANCE_SETTINGS';
export const CLEAR_COMMUNITY_APPEARANCE_SETTINGS =
  'CLEAR_COMMUNITY_APPEARANCE_SETTINGS';
// COMMUNITY SETTINGS END

// FORM SUNBMISSIONS START
export const FORM_SUBMISSION = 'FORM_SUBMISSION';
export const OPPORTUNITY_FILTERS = 'OPPORTUNITY_FILTERS';
export const CUSTOM_FIELD_FILTER_OUTPUT = 'CUSTOM_FIELD_FILTER_OUTPUT';
export const CUSTOM_FIELD_FILTER_OUTPUT_BULK =
  'CUSTOM_FIELD_FILTER_OUTPUT_BULK';
// FORM SUNBMISSIONS END

// ENTITIES START
export const LOAD_ALL_ENTITIES = 'LOAD_ALL_ENTITIES';
export const CLEAR_ALL_ENTITIES = 'CLEAR_ALL_ENTITIES';
// ENTITIES END

// UPDATE AUDIENCE START
export const LOAD_UPDATE_AUDIENCE = 'LOAD_UPDATE_AUDIENCE';
// UPDATE AUDIENCE END

// DYNAMIC TRANSLATION START
export const LOAD_DYNAMIC_TRANSLATION = 'LOAD_DYNAMIC_TRANSLATION';
// DYNAMIC TRANSLATION END

// IDEAS STATE START
export const UPDATE_SELECTED_LIST = 'UPDATE_SELECTED_LIST';
export const CLEAR_SELECTED_LIST = 'CLEAR_SELECTED_LIST';
// IDEAS STATE END

// SELECTED FILTER START
export const LOAD_SELECTED_FILTER = 'LOAD_SELECTED_FILTER';
// SELECTED FILTER END

// SELECTED COLUMN START
export const LOAD_SELECTED_COLUMN = 'LOAD_SELECTED_COLUMN';
// SELECTED COLUMN END
